language: python

install:
  - pip install tox==3.1.0

matrix:
  include:
    - name: "Python 3.6 UnitTests"
      python: 3.6
      script: tox -e py36
    - name: "Python 3.6 linter"
      python: 3.6
      script: tox -e pep8
    - name: "Python 3.7 UnitTests"
      python: 3.7
      dist: xenial
      sudo: true
      script: tox -e py37
    - name: "StandradJS linter for static/*.js"
      install: npm install -g standard
      script: standard "static/*.js" --global $ --global moment
