---
default:
  pipename: 'periodic-nightly'
  users_file: 'users_test.yml'
  secret_key: 'thisisverysecret'
  openid_provider: 'https://login.launchpad.net/+openid'
database:
  provider: 'mysql'
  host: '10.10.10.5'
  user: 'root'
  password: 'root'
  port: 3306
  name: 'zuul'
buildset:
  per_page: 20
  page_links: 4
  log_url: 'http://logs.opencontrail.org'
zuul:
  url: 'http://127.0.0.1:3000/'
  status_endpoint: 'static/status.json'
  pipelines:
    - check
    - gate
    - periodic-nightly
    - periodic-sanity
    - experimental
    - experimental-provision
  build_enqueue:
    pipelines:
      - periodic-nightly:
          - master
          - R5.0
  manager:
    host: '10.10.10.5'
    username: 'vagrant'
    user_key_file: 'acid/features/zuul_manager/tests/static/test_user_key' # ssh client key
    host_key_file: 'acid/features/zuul_manager/tests/static/host_key.pub' # file with fingerprint from host with zuul
    tenant: 'acid'
    trigger: 'timer'
    project: 'acid-test-dev'
    policy: 'AutoAddPolicy'
