---
default:
  pipename: 'periodic-nightly'
  users_file: 'users.yml'
  secret_key: 'thisisverysecret'
  openid_provider: 'https://login.launchpad.net/+openid'
database:
  provider: 'mysql'
  host: '10.10.10.5'
  user: 'root'
  password: 'root'
  port: 3306
  name: 'zuul'
buildset:
  per_page: 20
  page_links: 4
  log_url: 'http://logs.opencontrail.org'
zuul:
  url: 'http://localhost:3000/'
  status_endpoint: 'static/status.json'
  pipelines:
    - check
    - gate
    - periodic-nightly
    - periodic-sanity
    - experimental
    - experimental-provision
