---
default:
  pipename: 'periodic-nightly'
  users_file: 'users.yml'
  secret_key: b'\x8f\xa6gL\xc7\xc8\xe7\xf4v\xe8\xfc\xef\x85\xd3\xa6\x142\xc1\xc3\x12\xcc\xcfp['
  openid_provider: 'https://login.launchpad.net/+openid'
database:
  provider: 'mysql'
  host: '10.10.10.5'
  user: 'root'
  password: 'root'
  port: 3306
  name: 'zuul'
buildset:
  per_page: 20
  page_links: 4
  log_url: 'http://logs.opencontrail.org'
zuul:
  url: 'http://10.10.10.5/'
  status_endpoint: 'status.json'
  pipelines:
    - check
    - gate
    - periodic-nightly
    - periodic-sanity
    - experimental
    - experimental-provision
  build_enqueue:
    pipelines:
      - periodic-nightly:
          - master
          - R5.0
zuul_manager:
  host: '10.10.10.5'
  username: 'vagrant'
  user_key_file: '/etc/acid/insecure_private_key' # ssh client key
  host_key_file: 'zuul_host_key.pub' # file with fingerprint from host with zuul
  tenant: 'acid'
  trigger: 'timer'
  project: 'acid-test-dev'
  policy: 'AutoAddPolicy'
