---
- set_fact:
    galaxy_path: ~/.ansible/roles

- name: Check if zuul role exist
  stat:
    path: "{{ galaxy_path }}/openstack.zuul"
  register: openstack_role

- name: Delete openstack zuul role if it exist
  file: 
    state: absent
    path: "{{ galaxy_path }}/openstack.zuul"
  when: openstack_role.stat.exists == True

- name: Install zuul role from ansible galaxy
  shell: |
    set -e
    set -x
    ansible-galaxy install --roles-path {{ galaxy_path }} openstack.zuul
  args:
    executable: /bin/bash

- name: Deploy zuul.conf
  template:
    src: zuul.conf.j2
    dest: "{{ galaxy_path }}/openstack.zuul/templates/etc/zuul/zuul.conf"

- name: Deploy main.yaml file
  template:
    src: main.yaml.j2
    dest: "{{ galaxy_path }}/openstack.zuul/templates/etc/zuul/main.yaml"

- name: Change deploy method from PIP to GIT
  lineinfile:
    path: "{{ galaxy_path }}/openstack.zuul/defaults/main.yaml"
    regexp: "^zuul_install_method: pip"
    line: "zuul_install_method: git"
