---
- name: Change permissions for zuul.conf
  become: yes
  file:
    path: "/etc/zuul/zuul.conf"
    mode: 0644

- name: Set restart policy on failure for zuul-scheduler service
  become: yes
  lineinfile:
          path: /etc/systemd/system/zuul-scheduler.service
          insertafter: "^\\[Service\\]"
          line: "{{ item.comm }}={{ item.var}}"
  with_items:
          - { comm: "Restart", var: "on-failure" }
          - { comm: "RestartSec", var: "5" }

- name: Disable rate limiting for restarting zuul-scheduler service
  become: yes
  lineinfile:
          path: /etc/systemd/system/zuul-scheduler.service
          insertafter: "^\\[Unit\\]"
          line: "StartLimitIntervalSec=0"

