---
- name: "Create directory: /etc/docker"
  become: yes
  file:
    path: "/etc/docker"
    state: directory
    mode: a+rwx

- name: Copy daemon.json file
  become: yes
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"

- name: Add dockers official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Verify that key has a fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

- name: Set up repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes

- name: Install docker-compose
  become: yes
  apt:
    name: docker-compose
    state: present
    update-cache: yes

- name: Install pip2
  become: yes
  apt:
    name: python-pip
    state: present
    update_cache: yes

- name: Install docker for docker module
  become: yes
  pip:
    name: docker

- name: Verify docker installation
  shell: |
    set -e
    set -x
    docker --version
    docker-compose --version
  args:
    executable: /bin/bash