---
- name: Disable ssh Strict Host Key Checking
  become: yes
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: "StrictHostKeyChecking"
    line: "    StrictHostKeyChecking no"

- name: Copy host public key
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item }}"
  with_items:
    - ssh_host_ed25519_key
    - ssh_host_ed25519_key.pub
