---
- name: "Create gerrit directory"
  file:
    path: "{{ gerrit.home }}"
    state: directory
    mode: a+rwx
    recurse: true

- name: Create directories for Gerrit
  file:
    path: "{{ gerrit.home }}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - etc
    - .ssh

- name: Copy Gerrit configuration
  template:
    src: gerrit.config.j2
    dest: "{{ gerrit.home }}/etc/gerrit.config"

- name: Copy Gerrit host ssh key
  copy:
    src: "{{ item }}"
    dest: "{{ gerrit.home }}/etc/{{ item }}"
  with_items:
    - ssh_host_key
    - ssh_host_key.pub
    - authorized_keys

- name: Copy Gerrit admin ssh key
  copy:
    src: "{{ item }}"
    dest: "{{ gerrit.home }}/.ssh/{{ item }}"
  with_items:
    - admin_id_rsa
    - admin_id_rsa.pub

- name: Set chmod 600 on admin_id_rsa
  file:
    path: "{{ gerrit.home }}/.ssh/admin_id_rsa"
    mode: 0600

- name: Copy gerrit-compose.yaml file
  template:
    src: "gerrit-compose.yaml.j2"
    dest: "{{ gerrit.home }}/docker-compose.yaml"

- name: Copy and unarchive Gerrit db, index, and git files
  unarchive:
    src: "{{ item }}.tar.gz"
    dest: "{{ gerrit.home }}"
  with_items:
    - db
    - index
    - git

- name: Run gerrit container
  become: yes
  docker_service:
    project_src: "{{ gerrit.home }}"
    state: present

- name: Wait until gerrit comes up
  wait_for:
    delay: 6
    port: 8080
    msg: "Gerrit didn't start to listen on port 8080"
